export const topics = [
  { value: 'PHYSICS', label: 'Physics' },
  { value: 'CHEMISTRY', label: 'Chemistry' },
  { value: 'BIOLOGY', label: 'Biology' },
  { value: 'ASTRONOMY', label: 'Astronomy' },
  { value: 'NEUROSCIENCE', label: 'Neuroscience' },
  { value: 'GENETICS', label: 'Genetics' },
  { value: 'ROBOTICS', label: 'Robotics' },
  { value: 'ARTIFICIAL_INTELLIGENCE', label: 'AI' },
  { value: 'QUANTUM', label: 'Quantum' },
  { value: 'NANOTECHNOLOGY', label: 'Nanotechnology' },
  { value: 'BIOTECHNOLOGY', label: 'Biotechnology' },
  { value: 'SPACE', label: 'Space' },
  { value: 'CLIMATE', label: 'Climate' },
  { value: 'ECOLOGY', label: 'Ecology' },
  { value: 'OCEANOGRAPHY', label: 'Oceanography' },
  { value: 'PALEONTOLOGY', label: 'Paleontology' },
  { value: 'DAILY', label: 'Daily' },
  { value: 'OTHER', label: 'Other' }
] as const
